### ISSUE TITLE
Add facility for adding non-tracked files to the package archive 

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/ReleaseTools#48]
What I am thinking of is that the Semigroups package requires a copy of libsemigroups, which is not a part of the repository for Semigroups, and requires to be added to the archive by the release script. At present, the archive created by release tools would not contain libsemigroups, and so the wrapped package isn't be valid.

Would one way of doing this be to use `make dist` (part of the autoconf/make setup) to create the archive instead of `git archive`? This way any extra files required by the archive can be specified in `Makefile.am`.

**Comment by alex-konovalov** [comment]
I don't think that `git archive` is used to create an archive - e.g. autogenerated documentation files are non-tracked and included in the package distribution.

**Comment by alex-konovalov** [comment]
BTW I am also interested in this facility - I have some autogenerated test files which extract xamples from the manual, and I discovered that I have to keep them under version control to be included in the release.

**Comment by fingolfin** [comment]
I need ReleaseTools to work the way it does right now (and I consider automake and ˋmake distˋ an evolutionary dead end). However, I'd be happy to merge PRs which add *optional* features to e.g. use ˋmake distˋ, as long as I am not actively inconvenienced by them.

So e.g. you could add an option to activate additonal steps; and if that annoys you, you could also add reading in some kind of ˋ.releaseconfigˋ file, which the tools reads if present and derives extra settings from.

**Comment by fingolfin** [comment]
Also, as Alexander correctly stated, ˋgit archive` is only used to export a pristine copy of the files. Then, if present, `autogen.sh` is run; also `makedoc.g` or `doc/make_doc`, whichever is present.

That's of course somewhat arbitrary, but it was a pragmatic choice, as that was sufficent for a load of packages. But one could make it possible via an option and/or config file to execute additional or alternate commands at that step.

**Comment by fingolfin** [comment]
But just in case that wasn't clear: I currently have no plans to do so myself, as I have no need for it. PRs welcome!

**Comment by james-d-mitchell** [comment]
@fingolfin thanks for the comments. 

`make dist` was just a suggestion, I don't really have an opinion about its current or future use! 

Any suggestions for how to go about doing this in a way that would be useful more generally, such as for you @alex-konovalov? At present I hacked the release script to download the most recent version of libsemigroups from github and add that to the created archive, I'm struggling to see how I could do that with command line options without it being so cumbersome as to be unusable.  Happy to hear any suggestions.

**Comment by fingolfin** [comment]
Here is one way one might be able to do that (ideally with better names than I can come up with right now ;-):

Add an option `--run-pre-archive=path/to/some/exec`; that executable (if specified) then will be executed right after creating a clean-slate directory, i.e.:
```sh
...
notice "Exporting repository content for tag '$TAG'"
git archive --prefix="$BASENAME/" "$TAG" . | tar xf - -C "$TMP_DIR"

# Build the package documentation, run autoconf, etc.
cd "$TMP_DIR/$BASENAME"

# <--- RUN USER SCRIPT HERE (if one is given, and executable)

notice "Removing unnecessary files"
rm -f .git* .hg* .cvs*
....
```

Of course one could instead or also have options for an executable which is run *at the end* of this, i.e. after building the manual. And/or an option for an executable which is executed *instead*. However, I'd not add anything unless somebody actually needs it (following the motto that if you implement a feature nobody uses, you probably implement it wrong anyway. And wasted time ;-).

Then, since it is annoying to always have to specify that option when making a release, we could add support for `.releaseconfig` file -- if that is present in the repository, then we'll read additional setting from that. One can come up with lots of complicated things for that, but until we know about further uses, we could simply decide to "load" that file via `[[ -f .releaseconfig ]] && source .releaseconfig`, perhaps right after the option parsing and before the "Some initial sanity checks".

(Later on, one may wish for something else; but I don't know what exactly, and instead of trying to anticipate it, I'd keep it as simple as possible)

**Comment by james-d-mitchell** [comment]
@fingolfin awesome, make sense. I'll see what I can do.

**Comment by fingolfin** [comment]
Ah, and to make explicit what I only said between the lines above: the `--run-pre-archive` executable then would of course do whatever you need: invoke `make dist`, or download `libsemigroups` in some way, or a combination.

It would also make it trivial to resolve issue #49, as you could just insert an `rm -rf files-not-for-distribution` into that script.

**Comment by james-d-mitchell** [comment]
@fingolfin yes, of course, I got it.

**Comment by fingolfin** [comment]
@james-d-mitchell I assume you didn't find time for this, so I might pick this up now.

I thought that in the spirit of the "one-button-release" approach, instead of an option, I could just check for a file, say `.release`, and if that is present, execute it at the position indicated above. Thoughts?

**Comment by james-d-mitchell** [comment]
Sounds pretty reasonable to me. Sorry not to have found the time to actually do anything about this...
